### ISSUE TITLE
gh-pages website

### ISSUE THREAD

**Issue by mehulkar** [mehulkar/github-hall-of-fame#15]
Make a simple page that builds from the contents of the hall of fame. 

Not sure if `*.md` is the best format for entries if we're going
to dynamically build the list.

**Comment by chiefGui** [comment]
I can introduce a solution for the gh-pages if you agree.

Also, you're right – `.md` is not the most suitable format to work with, but I think we can create a simple API or just a vanilla JSON/YML to get the data available.

**Comment by mehulkar** [comment]
@chiefGui yeah, the idea of putting submissions in separate
files was to prevent the need for everyone to keep rebasing.
I think a JSON/YML data structure would be much better

**Comment by jnv** [comment]
May I suggest for your consideration [Jekyll collections](http://jekyllrb.com/docs/collections/)?

**Comment by chiefGui** [comment]
@jnv I don't think we have to go too deep to get things done. I mean, the project is simple and I thought to create a gh-page using vanilla HTML – no Jekyll; no third-party platforms or libraries which make the site for you.

Furthermore, I'm not devaluing Jekyll and its power. I'm just saying we don't need it in this first moment. We could create a (very) simple API to propagate JSON and then our application consumes it – simple, clean and without hard dependencies.

And by reading Jekyll Collections, I think we'll get stuck over the time, mainly because of this:

> Collections support is unstable and may change

@mehulkar What do you think to create a simple, seamlessly API?

**Comment by jnv** [comment]
@chiefGui The simplicity is in the eye of the beholder. For example vanilla HTML or JSON data is a simple solution from a technical point of view, but more complicated for contributors.

To be honest, in my opinion _any_ kind of API or even HTML page is an unnecessary complication here. Just drop the stuff into the README, maybe add some maintenance script to sort items for you and that's it. It works for [humongous lists](https://github.com/ziadoz/awesome-php), it will work for you too, especially once the initial influx of PRs have slowed down and the basic categories have been established.

**Comment by mehulkar** [comment]
@chiefGui sounds like overkill to me :)
I started doing some work on `gh-pages` branch yesterday. I didn't understand what a Jekyll collection was, so I just used their data sets feature that I was already familiar with. 
https://github.com/mehulkar/github-hall-of-fame/commits/gh-pages

**Comment by mehulkar** [comment]
Added barebones website at `gh-pages` branch. Porting over recent submissions and then removing master branch altogether

**Comment by mehulkar** [comment]
Rebased on master (to preserve original contributors), and made terrible looking website. Have at it, world!
